config/routes.rb
Rails.application.routes.draw do
  resources :servicos

  get 'home/index'

  devise_for :usuarios

  root 'home#index'

end

app/models/servico.rb
class Servico < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @servicos = Servico.all
  end
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :set_servico, only: [:show, :edit, :update, :destroy]

  # GET /servicos
  # GET /servicos.json
  def index
    @servicos = Servico.all
  end

  # GET /servicos/1
  # GET /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
  end

  # GET /servicos/1/edit
  def edit
  end

  # POST /servicos
  # POST /servicos.json
  def create
    @servico = Servico.new(servico_params)

    respond_to do |format|
      if @servico.save
        format.html { redirect_to @servico, notice: 'Servico was successfully created.' }
        format.json { render :show, status: :created, location: @servico }
      else
        format.html { render :new }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servicos/1
  # PATCH/PUT /servicos/1.json
  def update
    respond_to do |format|
      if @servico.update(servico_params)
        format.html { redirect_to @servico, notice: 'Servico was successfully updated.' }
        format.json { render :show, status: :ok, location: @servico }
      else
        format.html { render :edit }
        format.json { render json: @servico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servicos/1
  # DELETE /servicos/1.json
  def destroy
    @servico.destroy
    respond_to do |format|
      format.html { redirect_to servicos_url, notice: 'Servico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def servico_params
      params.require(:servico).permit(:titulo, :desc_curta, :desc_longa)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/home/index.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        Bem-vindo à GarageSoft!
      </h1>
    </div>
    <% @servicos.each do |servico| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4><%= servico.titulo %></h4>
        </div>
        <div class="panel-body">
          <p><%= servico.desc_curta %></p>
          <%= link_to "Saiba mais", servico, :class => "btn btn-default" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <!-- /.row -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garagesoft</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Garagesoft", root_path, :class => "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="about.html">Sobre</a></li>
          <li><%= link_to "Serviços", servicos_path %></li>
          <li>
            <a href="contact.html">Contato</a>
          </li>
          <li>
            <a href="#">Portfolio</a>
          </li>
          <li>
            <a href="#">Blog</a>
          </li>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
  <%= yield %>
  <hr>

  <!-- Footer -->
  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; GarageSoft 2014</p>
      </div>
    </div>
  </footer>

</div>
<!-- /.container -->


<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!-- Script to Activate the Carousel -->
<script>
$('.carousel').carousel({
        interval: 5000 //changes the speed
      })
</script>
</body>
</html>

app/views/servicos/_form.html.erb
<%= form_for(@servico) do |f| %>
  <% if @servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servico.errors.count, "error") %> prohibited this servico from being saved:</h2>

      <ul>
      <% @servico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :desc_curta %><br>
    <%= f.text_area :desc_curta %>
  </div>
  <div class="field">
    <%= f.label :desc_longa %><br>
    <%= f.text_area :desc_longa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicos/edit.html.erb
<h1>Editing servico</h1>

<%= render 'form' %>

<%= link_to 'Show', @servico %> |
<%= link_to 'Back', servicos_path %>

app/views/servicos/index.html.erb
<!-- Page Content -->
<div class="container">

  <!-- Page Heading/Breadcrumbs -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Serviços
        <small>O que nós fazemos?</small>
      </h1>
      <ol class="breadcrumb">
        <li><%= link_to "GarageSoft", root_path %></li>
        <li class="active">Serviços</li>
      </ol>
    </div>
  </div>
  <!-- /.row -->
  <!-- Service Tabs -->
  <div class="row">
    <div class="col-lg-12">
      <ul id="myTab" class="nav nav-tabs nav-justified">
        <% @servicos.each_with_index do |servico, index| %>
        <li <% if index == 0 %>class="active"<% end %>><a href="#servico-<%= servico.id %>" data-toggle="tab"><%= servico.titulo %></a>
        </li>
        <% end %>
      </ul>
      <div id="myTabContent" class="tab-content">
        <% @servicos.each_with_index do |servico, index| %>
        <div class="tab-pane fade <% if index == 0 %>active<% end %> in" id="servico-<%= servico.id %>">
          <h4><%= servico.titulo %></h4>
          <%= servico.desc_curta %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <br>
  <% if current_usuario %>
  <%= link_to 'New Servico', new_servico_path %>
  <% end %>

app/views/servicos/new.html.erb
<h1>New servico</h1>

<%= render 'form' %>

<%= link_to 'Back', servicos_path %>

app/views/servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @servico.titulo %>
</p>

<p>
  <strong>Desc curta:</strong>
  <%= @servico.desc_curta %>
</p>

<p>
  <strong>Desc longa:</strong>
  <%= @servico.desc_longa %>
</p>

<%= link_to 'Edit', edit_servico_path(@servico) %> |
<%= link_to 'Back', servicos_path %>